### ISSUE TITLE
Filter by faction

### ISSUE THREAD

**Issue by r4dian** [AlexRaubach/MetaWing#7]
Please add the ability to filter by faction, or include faction info in the exported .csv files if it is possible.

**Comment by AlexRaubach** [comment]
Looks like factions are present in the ship_combos csv but aren't present in pilots or ships. Adding the factions to those two csvs should be easy, adding an additional option to the filter bar wound take a lot longer due to how much it touches. 

I can't make any promises but I'll try to look into the CSVs at least.

**Comment by AlexRaubach** [comment]
I added the factions to the csv and json exports of ships 887d4778be418d2401b86e05d5fa00c227381d2e  and pilots 5127f6563f90381464dcfa784de0ad70bb33ff9f 819601f3a75bc441730411d5a2c95900d64a93b9

Adding a faction dropdown to the filterbar would be a lot more work and I just don't have the time to do it now but I'll leave the issue open and maybe someone else will decide to pick it up or I'll revisit it in the future.

**Comment by r4dian** [comment]
Thanks, having it in the export suits my purpose fine, 👍.
