### ISSUE TITLE
Some list from worlds are missing

### ISSUE THREAD

**Issue by Alaedar** [AlexRaubach/MetaWing#82]
Hello ! As the title say, some list from the world championship are missing
https://listfortress.com/tournaments/3620

For example, the 33rd list is missing when we check in Metawing

https://meta.listfortress.com/ship_combos/4623/squadrons?ranking_start=2022-12-01&format_id=36&

Thank you ! :D

**Comment by AlexRaubach** [comment]
Hey, thanks for creating an issue for this. What happened is two people submitted lists made in a version of LBN that had an invalid xws name for Mauler Mithel BOY pilot. The incorrect data in ListFortress was then passed to Metawing, which choked because it couldn't find a pilot with that name. That meant that all remaining tournament participants (not sure how they're ordered) weren't imported into metawing because whenever Haslo made the importer many years ago, he didn't stick each user import into a try catch block and no one has bothered to fix it. TBH to him, listjuggler was storing list data in a relational database so each pilot is either correct or not while I'm just storing the xws json which means my data quality is a lot worse.

I've created an issue #83  to deal with the root cause and I'll try out my initial solution this weekend and see if it actually works or if the problem is more complicated than it seems.
