### ISSUE TITLE
Add 2.0 Legacy formats to filter

### ISSUE THREAD

**Issue by SogeMoge** [AlexRaubach/MetaWing#86]
Since the end of X-Wing development many players turned back to 2.0 Legacy and more tournaments are coming. Appropriate Legacy filter will be a huge contribution for the X-Wing community.

**Comment by Don-Padron** [comment]
I second that. 2.0 Legacy Standard Format & 2.0 Legacy Wild Space are available Formats in ListFortress, it would be awesome to also have them available in MetaWing. Thanks.

**Comment by AlexRaubach** [comment]
There are [just a handful of legacy standard tournaments](https://listfortress.com/tournaments?min_participants=&max_participants=&format_id=37&tournament_type_id=&country=&name_search=&played_after=&played_before=&sort_order=) on ListFortress this year and zero Wildspace tournaments since I added it as a format. I don't think that there is enough data to really justify the effort required for me to dig into the MW codebase and figure out what's going on. 

I'm already paying a couple hundred bucks a year out of my own pocket in server costs. Since I no longer play it's tough to justify spending literally hundreds of dollars worth of my time on non-essential maintenance or new features.

**Comment by Don-Padron** [comment]
Ok, that's understandable. Thanks for the reply and keeping MW going.
